### ISSUE TITLE
Microshed with quarkus 1.12.2-Final cant initialize PostgreSQLContainer

### ISSUE THREAD

**Issue by tiagomistral** [MicroShed/microshed-testing#261]
**Describe the bug**
When we try run the quarkus app with a new version of quarkus it fails.

`Caused by: io.quarkus.builder.BuildException:
Build failure: Build failed due to errors
	[error]: Build step io.quarkus.agroal.deployment.AgroalProcessor#build threw an exception: io.quarkus.runtime.configuration.ConfigurationException: quarkus.datasource.url and quarkus.datasource.driver have been deprecated in Quarkus 1.3 and removed in 1.9. Please use the new datasource configuration as explained in https://quarkus.io/guides/datasource.
	at io.quarkus.agroal.deployment.AgroalProcessor.build(AgroalProcessor.java:78)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:920)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2415)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
	at java.base/java.lang.Thread.run(Thread.java:834)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)`

**To Reproduce**
Checkout the quarkus-demo
Update quarkus.platform.version and quarkus-plugin.version to 1.12.2.Final on pom.xml
run 'mvn test'

**Expected behavior**
Expect a build with all test with success

**System information:**
 - OS: Mac
 - Java Version: 11
 - MicroShed Testing Version: 0.9.1

**Comment by appiepollo14** [comment]
Solved since 0.9.2
